COMMENT = _{ (("#" | ";") ~ (!NEWLINE ~ ANY)*) ~ NEWLINE }
WHITESPACE = _{ " " | "\t" | "\r" }

identifier = _{ XID_START ~ XID_CONTINUE* }

section_header = { identifier }

key = { identifier }
value_line = @{ (!(NEWLINE | "\\\n" ) ~ ANY)* }
value = { ( value_line ~ "\\\n")* ~ value_line }

entry = { key ~ "=" ~ value ~ NEWLINE+ }

section = { "[" ~ section_header ~ "]" ~ NEWLINE ~ entry+ }

unit_file = { SOI ~ section + ~ EOI }